# Generated by Django 6.0 on 2025-12-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_enrollment_completed_enrollment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of course requirements'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of course tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, help_text='List of target audience descriptions'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list, help_text='List of learning outcomes'),
        ),
    ]
